[package]
name = "pace_example"
version = "0.0.1"
edition = "2021"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"

[dependencies]
nersent_pace = { path = "../pace" }
chrono = "0.4.23"

