name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      CARGO_TERM_COLOR: always

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          access_token: ${{ github.token }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: actions/cache@v3
        name: Yarn cache
        id: yarn-cache
        continue-on-error: false
        with:
          path: |
            node_modules
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Node.js dependencies
        run: yarn install --prefer-offline --frozen-lockfile
        env:
          ADBLOCK: true

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          override: true

      - name: Install Rust tools
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        continue-on-error: false
        with:
          prefix-key: "rust-cache"

      - name: Lint
        run: cargo fmt --all -- --check
        # && cargo clippy -- -D warnings

      - name: Test
        run: cargo nextest run
