overrides:
  bazed: link:../../../Users/xnerh/AppData/Local/pnpm/global/5/node_modules/@nersent/bazed
  '@nersent/bazed': link:../../../Users/xnerh/AppData/Local/pnpm/global/5/node_modules/@nersent/bazed
