# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sym.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'sym.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tsym.proto\"\x1b\n\rGetSymRequest\x12\n\n\x02id\x18\x01 \x01(\t\"#\n\x0eGetSymResponse\x12\x11\n\x03sym\x18\x01 \x01(\x0b\x32\x04.Sym\"\x9b\x03\n\x03Sym\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x06prefix\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08\x63urrency\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x1a\n\rbase_currency\x18\x04 \x01(\tH\x02\x88\x01\x01\x12\x13\n\x06ticker\x18\x05 \x01(\tH\x03\x88\x01\x01\x12\x16\n\tticker_id\x18\x06 \x01(\tH\x04\x88\x01\x01\x12\x14\n\x07\x63ountry\x18\x07 \x01(\tH\x05\x88\x01\x01\x12\x15\n\x08min_tick\x18\x08 \x01(\x01H\x06\x88\x01\x01\x12\x14\n\x07min_qty\x18\t \x01(\x01H\x07\x88\x01\x01\x12\x18\n\x0bprice_scale\x18\n \x01(\x01H\x08\x88\x01\x01\x12\x18\n\x0bpoint_value\x18\x0b \x01(\x01H\t\x88\x01\x01\x12\x14\n\x05icons\x18\x0c \x03(\x0b\x32\x05.IconB\t\n\x07_prefixB\x0b\n\t_currencyB\x10\n\x0e_base_currencyB\t\n\x07_tickerB\x0c\n\n_ticker_idB\n\n\x08_countryB\x0b\n\t_min_tickB\n\n\x08_min_qtyB\x0e\n\x0c_price_scaleB\x0e\n\x0c_point_value\"&\n\x04Icon\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x11\n\tmime_type\x18\x02 \x01(\t20\n\x06SymApi\x12&\n\x03Get\x12\x0e.GetSymRequest\x1a\x0f.GetSymResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sym_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETSYMREQUEST']._serialized_start=13
  _globals['_GETSYMREQUEST']._serialized_end=40
  _globals['_GETSYMRESPONSE']._serialized_start=42
  _globals['_GETSYMRESPONSE']._serialized_end=77
  _globals['_SYM']._serialized_start=80
  _globals['_SYM']._serialized_end=491
  _globals['_ICON']._serialized_start=493
  _globals['_ICON']._serialized_end=531
  _globals['_SYMAPI']._serialized_start=533
  _globals['_SYMAPI']._serialized_end=581
# @@protoc_insertion_point(module_scope)
