[package]
name = "pace_bench"
version = "0.0.1"
edition = "2021"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"

[dependencies]
mimalloc = { version = "0.1.34", default-features = false }
kdam = "0.3.0"
serde_json = "1.0"
serde = "1.0"
nersent_pace = { path = "../../pace" }
